import { defineConfig } from "unocss";
import presetUno from "@unocss/preset-uno";
import presetAttributify from "@unocss/preset-attributify";
import presetTypography from "@unocss/preset-typography";
import transformerDirectives from "@unocss/transformer-directives";
import transformerVariantGroup from "@unocss/transformer-variant-group";

export default defineConfig({
    presets: [presetUno(), presetAttributify(), presetTypography()],
    transformers: [transformerDirectives(), transformerVariantGroup()],
    theme: {
        colors: {
            red: {
                0: "var(--color-red-0)",
                1: "var(--color-red-1)",
                2: "var(--color-red-2)",
                3: "var(--color-red-3)",
                4: "var(--color-red-4)",
                5: "var(--color-red-5)",
                6: "var(--color-red-6)",
                7: "var(--color-red-7)",
                8: "var(--color-red-8)",
                9: "var(--color-red-9)",
            },
            pink: {
                0: "var(--color-pink-0)",
                1: "var(--color-pink-1)",
                2: "var(--color-pink-2)",
                3: "var(--color-pink-3)",
                4: "var(--color-pink-4)",
                5: "var(--color-pink-5)",
                6: "var(--color-pink-6)",
                7: "var(--color-pink-7)",
                8: "var(--color-pink-8)",
                9: "var(--color-pink-9)",
            },
            grape: {
                0: "var(--color-grape-0)",
                1: "var(--color-grape-1)",
                2: "var(--color-grape-2)",
                3: "var(--color-grape-3)",
                4: "var(--color-grape-4)",
                5: "var(--color-grape-5)",
                6: "var(--color-grape-6)",
                7: "var(--color-grape-7)",
                8: "var(--color-grape-8)",
                9: "var(--color-grape-9)",
            },
            violet: {
                0: "var(--color-violet-0)",
                1: "var(--color-violet-1)",
                2: "var(--color-violet-2)",
                3: "var(--color-violet-3)",
                4: "var(--color-violet-4)",
                5: "var(--color-violet-5)",
                6: "var(--color-violet-6)",
                7: "var(--color-violet-7)",
                8: "var(--color-violet-8)",
                9: "var(--color-violet-9)",
            },
            indigo: {
                0: "var(--color-indigo-0)",
                1: "var(--color-indigo-1)",
                2: "var(--color-indigo-2)",
                3: "var(--color-indigo-3)",
                4: "var(--color-indigo-4)",
                5: "var(--color-indigo-5)",
                6: "var(--color-indigo-6)",
                7: "var(--color-indigo-7)",
                8: "var(--color-indigo-8)",
                9: "var(--color-indigo-9)",
            },
            blue: {
                0: "var(--color-blue-0)",
                1: "var(--color-blue-1)",
                2: "var(--color-blue-2)",
                3: "var(--color-blue-3)",
                4: "var(--color-blue-4)",
                5: "var(--color-blue-5)",
                6: "var(--color-blue-6)",
                7: "var(--color-blue-7)",
                8: "var(--color-blue-8)",
                9: "var(--color-blue-9)",
            },
            cyan: {
                0: "var(--color-cyan-0)",
                1: "var(--color-cyan-1)",
                2: "var(--color-cyan-2)",
                3: "var(--color-cyan-3)",
                4: "var(--color-cyan-4)",
                5: "var(--color-cyan-5)",
                6: "var(--color-cyan-6)",
                7: "var(--color-cyan-7)",
                8: "var(--color-cyan-8)",
                9: "var(--color-cyan-9)",
            },
            teal: {
                0: "var(--color-teal-0)",
                1: "var(--color-teal-1)",
                2: "var(--color-teal-2)",
                3: "var(--color-teal-3)",
                4: "var(--color-teal-4)",
                5: "var(--color-teal-5)",
                6: "var(--color-teal-6)",
                7: "var(--color-teal-7)",
                8: "var(--color-teal-8)",
                9: "var(--color-teal-9)",
            },
            green: {
                0: "var(--color-green-0)",
                1: "var(--color-green-1)",
                2: "var(--color-green-2)",
                3: "var(--color-green-3)",
                4: "var(--color-green-4)",
                5: "var(--color-green-5)",
                6: "var(--color-green-6)",
                7: "var(--color-green-7)",
                8: "var(--color-green-8)",
                9: "var(--color-green-9)",
            },
            lime: {
                0: "var(--color-lime-0)",
                1: "var(--color-lime-1)",
                2: "var(--color-lime-2)",
                3: "var(--color-lime-3)",
                4: "var(--color-lime-4)",
                5: "var(--color-lime-5)",
                6: "var(--color-lime-6)",
                7: "var(--color-lime-7)",
                8: "var(--color-lime-8)",
                9: "var(--color-lime-9)",
            },
            yellow: {
                0: "var(--color-yellow-0)",
                1: "var(--color-yellow-1)",
                2: "var(--color-yellow-2)",
                3: "var(--color-yellow-3)",
                4: "var(--color-yellow-4)",
                5: "var(--color-yellow-5)",
                6: "var(--color-yellow-6)",
                7: "var(--color-yellow-7)",
                8: "var(--color-yellow-8)",
                9: "var(--color-yellow-9)",
            },
            orange: {
                0: "var(--color-orange-0)",
                1: "var(--color-orange-1)",
                2: "var(--color-orange-2)",
                3: "var(--color-orange-3)",
                4: "var(--color-orange-4)",
                5: "var(--color-orange-5)",
                6: "var(--color-orange-6)",
                7: "var(--color-orange-7)",
                8: "var(--color-orange-8)",
                9: "var(--color-orange-9)",
            },
            primary: {
                0: "var(--color-primary-0)",
                1: "var(--color-primary-1)",
                2: "var(--color-primary-2)",
                3: "var(--color-primary-3)",
                4: "var(--color-primary-4)",
                5: "var(--color-primary-5)",
                6: "var(--color-primary-6)",
                7: "var(--color-primary-7)",
                8: "var(--color-primary-8)",
                9: "var(--color-primary-9)",
            },
            secondary: {
                0: "var(--color-secondary-0)",
                1: "var(--color-secondary-1)",
                2: "var(--color-secondary-2)",
                3: "var(--color-secondary-3)",
                4: "var(--color-secondary-4)",
                5: "var(--color-secondary-5)",
                6: "var(--color-secondary-6)",
                7: "var(--color-secondary-7)",
                8: "var(--color-secondary-8)",
                9: "var(--color-secondary-9)",
            },
            info: {
                100: "#e0f2fe",
                200: "#bae6fd",
                300: "#7dd3fc",
                400: "#38bdf8",
                500: "#0ea5e9",
                600: "#0284c7",
                700: "#0369a1",
                800: "#075985",
                900: "#0c4a6e",
            },
            success: {
                100: "#d1fae5",
                200: "#a7f3d0",
                300: "#6ee7b7",
                400: "#34d399",
                500: "#10b981",
                600: "#059669",
                700: "#047857",
                800: "#065f46",
                900: "#064e3b",
            },
            warning: {
                100: "#fff7ed",
                200: "#ffedd5",
                300: "#fed7aa",
                400: "#fdba74",
                500: "#fb923c",
                600: "#f97316",
                700: "#ea580c",
                800: "#c2410c",
                900: "#9a3412",
            },
            error: {
                100: "#fee2e2",
                200: "#fecaca",
                300: "#fca5a5",
                400: "#f87171",
                500: "#ef4444",
                600: "#dc2626",
                700: "#b91c1c",
                800: "#991b1b",
                900: "#7f1d1d",
            },
        },
    },
});
